/**
 * gallery.js — renders gamepad/gallery/manifest.json as a grid.
 *
 * The manifest is generated by `node scripts/generate-gallery.js`, so the
 * published gallery is whatever is committed under gallery/images/.
 */

const grid      = document.getElementById('g-grid');
const status    = document.getElementById('g-status');
const countEl   = document.getElementById('g-count');
const lightbox  = document.getElementById('g-lightbox');
const lbImg     = document.getElementById('g-lightbox-img');
const lbCaption = document.getElementById('g-lightbox-caption');

try {
  const res = await fetch('./manifest.json', { cache: 'no-cache' });
  if (!res.ok) throw new Error(`manifest.json → HTTP ${res.status}`);
  const { images } = await res.json();
  render(images ?? []);
} catch (err) {
  status.innerHTML = `Could not load the gallery manifest.<br>${err.message}`;
}

function render(images) {
  countEl.textContent = `${images.length} image${images.length !== 1 ? 's' : ''}`;

  if (images.length === 0) {
    status.innerHTML =
      'Nothing here yet.<br>Save a drawing, drop the PNG in ' +
      '<code>gamepad/gallery/images/</code>,<br>then run ' +
      '<code>node scripts/generate-gallery.js</code>.';
    return;
  }

  grid.innerHTML = '';

  for (const img of images) {
    const card = document.createElement('figure');
    card.className = 'g-card';
    card.tabIndex = 0;

    const thumb = document.createElement('img');
    thumb.src = `./images/${img.file}`;
    thumb.alt = img.title;
    thumb.loading = 'lazy';
    thumb.decoding = 'async';

    const caption = document.createElement('figcaption');
    caption.innerHTML = `
      <span class="g-card__title"></span>
      <span class="g-card__date"></span>
    `;
    caption.querySelector('.g-card__title').textContent = img.title;
    caption.querySelector('.g-card__date').textContent  = img.date ?? '';

    card.append(thumb, caption);

    if (img.note) {
      const note = document.createElement('p');
      note.className = 'g-card__note';
      note.textContent = img.note;
      card.appendChild(note);
    }

    const open = () => showLightbox(img);
    card.addEventListener('click', open);
    card.addEventListener('keydown', e => {
      if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open(); }
    });

    grid.appendChild(card);
  }
}

// ── Lightbox ─────────────────────────────────────────────────────────────────

function showLightbox({ file, title, date, note }) {
  lbImg.src = `./images/${file}`;
  lbImg.alt = title;
  lbCaption.textContent = [title, date, note].filter(Boolean).join('  ·  ');
  lightbox.hidden = false;
}

function hideLightbox() {
  lightbox.hidden = true;
  lbImg.src = '';
}

lightbox.addEventListener('click', hideLightbox);
document.addEventListener('keydown', e => {
  if (e.key === 'Escape' && !lightbox.hidden) hideLightbox();
});
